spring:
  sql:
    init:
      mode: always
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: false
        format_sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/quanligiaotrinh?createDatabaseIfNotExist=true&autoReconnect=true&userSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8881
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
